### ISSUE TITLE
Slider not showing on page 2?

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zillah#108]
@claudiuvertistudio this is how it was designed? To not show the slider on frontpage on the second, third etc pages, if there are more posts 

http://prntscr.com/bgan32

**Comment by ineagu** [comment]
it should be there as well I think

**Comment by claudiuvertistudio** [comment]
The slider is only on first page

**Comment by claudiuvertistudio** [comment]
@ineagu Why should appear on the second page? If you want this behaviour I will implement it.

**Comment by ineagu** [comment]
up to you

On Mon, Jul 4, 2016 at 9:47 AM, Claudiu Buruiana <notifications@github.com>
wrote:

> @ineagu <https://github.com/ineagu> Why should appear on the second page?
> If you want this behaviour I will implement it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/zillah/issues/108#issuecomment-230226638>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DFmJnBgqawsznkgGT2YMJE0o5c5mks5qSLqDgaJpZM4I1cYG>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
