### ISSUE TITLE
Things missing on single

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zillah#11]
1) Display date, nr of comments, author (either in header or at the end as author box info )
2) Display related posts
3) How do we display tags ? Right now they aren't showing

**Comment by rodica-andronache** [comment]
@ineagu I think those were not in the html/design. Will you ask Asley to add them, or we need to do this?

**Comment by ineagu** [comment]
I have asked ashley for design

On Mon, May 9, 2016 at 2:33 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> I think those were not in the
> html/design. Will you ask Asley to add them, or we need to do this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zillah/issues/11#issuecomment-217851895>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
