### ISSUE TITLE
Slider issue when one post

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/zillah#111]
When you haveone post and slider is active, nothing appears.

**Comment by HardeepAsrani** [comment]
Also not working properly with 3 posts. So it should have an even number of posts for it to work.

**Comment by claudiuvertistudio** [comment]
The slider appears if there are more than two posts because one slide contans two slides. The last one appears only if the number of slider are multiple of two.

**Comment by HardeepAsrani** [comment]
@claudiuvertistudio Yes, I get that. That's what I meant. If the number of posts isn't even, then the odd one should appear in the blog, instead of not appeared anywhere. :)
