### ISSUE TITLE
Theme quality

### ISSUE THREAD

**Issue by szepeviktor** [Codeinwp/zillah#115]
http://themecheck.org/score/wordpress-theme-zillah.html

Good morning!

Would it be possible to work for you full time?
https://github.com/szepeviktor/wordpress-plugin-construction
https://profiles.wordpress.org/szepeviktor/#content-plugins

**Comment by s2abina** [comment]
Hey Viktor, thank you for your interest in working with us, actually, we will be soon hiring, soon. I will let you know where you can apply!

**Comment by s2abina** [comment]
This is our newest opening: https://themeisle.workable.com/jobs/285111 

It's based in Bucharest, but you can check it out.

**Comment by szepeviktor** [comment]
Thank you Sabina.
You may call me on Skype after reading my answers.
