### ISSUE TITLE
Smaller header on mobile

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zillah#118]
@claudiuvertistudio I think on mobile there is no point to have the header, do you think is a good idea ( possible ) to move the whole logo+ description if exist in the top menu ? like smashingmagazine.com and show directly the article ?

I think this is the best approach for all our themes for single articles.

cc @s2abina @rodica-andronache @abaicus @cristian-ungureanu thoughts ?

**Comment by s2abina** [comment]
It;s easy for SmashingMagazine to elude this, as their website is really popular and many people already know SmashingMag = design.
For smaller websites/brands, it will make sense to have a line to explain what the site is about.

Could we keep the header on the main blog page, and take it out when you are in a particular blog-post?

**Comment by abaicus** [comment]
I think that really should be an option. To remove it from all the pages except the homepage.

**Comment by ineagu** [comment]
ok, what about hiding header on single by default and add an option to show
header on single ? ( on mobile only )

On Thu, Jun 30, 2016 at 10:00 AM, Andrei Băicuș <notifications@github.com>
wrote:

> I think that really should be an option. To remove it from all the pages
> except the homepage.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/zillah/issues/118#issuecomment-229589147>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DKQ47vXS14pEe-xx-6LhUNM6ONesks5qQ3eIgaJpZM4JBS73>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by abaicus** [comment]
That would actually be better. As there's where the issue occurs.
