### ISSUE TITLE
Smaller article meta on mobile

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zillah#119]
@claudiuvertistudio looks like on mobile the article meta is still taking too much space. 

I was doing some tests that something that will work better is : 

font-size: 1.2em;
line-height: 25px;
no text transform-uppercase;
text-align:left

For categories : 

0.8375em font-size

**Comment by claudiuvertistudio** [comment]
i don't understand, on what page? single page?

**Comment by ineagu** [comment]
yep, single
