### ISSUE TITLE
Recommend JetPack for ( sharing icons, related posts, contact form )

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zillah#12]

**Comment by rodica-andronache** [comment]
@ineagu how shoud we recommend this? you mean with tgm? or we'll have an about zillah page?

**Comment by ineagu** [comment]
tgm . ( take a look how : Canape theme from w.org repo is doing )

On Mon, May 9, 2016 at 2:27 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> how shoud we recommend this? you mean
> with tgm? or we'll have an about zillah page?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zillah/issues/12#issuecomment-217850623>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
