### ISSUE TITLE
Slider isn't moving

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zillah#120]
@claudiuvertistudio when the page loads, doesn't matter how much time you wait the slider isn't moving, if you manually switch it to 2nd position, it works after.

**Comment by claudiuvertistudio** [comment]
@ineagu I have tested and it seems to work well. Maybe you have the cursor over the slider.

**Comment by ineagu** [comment]
ok, you can close this :)

On Thu, Jul 7, 2016 at 9:53 AM, Claudiu Buruiana <notifications@github.com>
wrote:

> @ineagu <https://github.com/ineagu> I have tested and it seems to work
> well. Maybe you have the cursor over the slider.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/zillah/issues/120#issuecomment-231008246>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DEXNW_ke8GC6PUO36XcDc0mCnNxmks5qTLBggaJpZM4JC71z>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
