### ISSUE TITLE
Sync dev2/demo git

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zillah#14]
http://dev2.themeisle.com/zillah/
http://demo.themeisle.com/zillah/
http://themeisle.com/themes/zillah

@ineagu we'll have a themeisle page for zillah?

**Comment by ineagu** [comment]
yep

On Mon, May 9, 2016 at 11:23 AM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> http://dev2.themeisle.com/zillah/
> http://demo.themeisle.com/zillah/
>
> @ineagu <https://github.com/ineagu> we'll have a themeisle page for
> zillah?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zillah/issues/14>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
@selu91 From now on, to syncronize dev2/demo I only need to add it in that new update system, like you showed me?

**Comment by selu91** [comment]
yes, exactly :D

**Comment by selu91** [comment]
you need to have the repo and setting for the webhook. The demo and dev2 folder will be created automatically
