### ISSUE TITLE
Sidebar not showing on mobile

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/zillah#149]
@rodica-andronache

**Comment by ineagu** [comment]
This was by design.

**Comment by ineagu** [comment]
@rodica-andronache do we have an advanced section to add an option to show sidebar on mobile ? or what do you think about adding a new widget area specially for mobile ?

**Comment by rodica-andronache** [comment]
@ineagu we can add an option near the option to show the sidebar on desktop http://prntscr.com/d5243d .

**Comment by ineagu** [comment]
I would just modify the code so when the cureent setting is checked we also show the sidebar on mobile after content

**Comment by rodica-andronache** [comment]
ok
