### ISSUE TITLE
Review theme

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zillah#150]
and make sure there are no security/escaping issues before wp.org review

**Comment by rodica-andronache** [comment]
@cristian-ungureanu can you please review the theme, and see if you find security related issues, like escaping etc ? This task is just for testing. We need to make sure we don't have security issues, so that the reviewers don't close our ticket on wp.org

**Comment by rodica-andronache** [comment]
check with the development branch

**Comment by cristian-ungureanu** [comment]
@rodica-andronache ,the sanitization for palette picker isn't right. I can fix that or I can remove the palette picker control and add the one in twentysixteen, maybe modify it to show the colors in dropdown as we do now. The one in twentysixteen have a better UX. Every color from a palette can be changed.
I will continue my review tomorrow. Please let me know what to do here.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu how long would it take to change it?
@ineagu what do you think?

**Comment by ineagu** [comment]
Depends how long will take, I am tempted just to fix curent implementation as well, zillah is not very successfull
