### ISSUE TITLE
add latest updated date to posts

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zillah#166]
We can have an option for blog to display the latest updated date with the proper html markup, since sometimes we want this to be picked up in google.

We need it for Themeisle blog

**Comment by ineagu** [comment]
cc @rodica-andronache

**Comment by ineagu** [comment]
I need this :D

**Comment by abaicus** [comment]
@ineagu There's going to be an option in customizer to activate this when this is merged into production. 👍

**Comment by ineagu** [comment]
The issue here with last modified datewhich is failing is the fact that parent schema.org structure is missing ( blogpost)

**Comment by abaicus** [comment]
@ineagu got it. I'll solve this asap.

**Comment by ineagu** [comment]
if you wanna work on it here is a good structure : 

<article itemscope itemtype="https://schema.org/BlogPosting">
<header>
<h1 itemprop="headline"><?php the_title(); ?></h1>
<time pubdate itemprop="datePublished" datetime="<?php the_time( 'c' ); ?>" content="<?php the_time( 'c' ); ?>">
<?php the_time( get_option( 'date_format' ) ); ?>
</time>
 
<div>Categories: <span itemprop="about"><?php the_category(', '); ?></span></div>
<div>Tags: <span itemprop="keywords"><?php the_tags(''); ?></span></div>
 
<div itemprop="author" itemscope itemtype="https://schema.org/Person">
<img itemprop="image" src="<?php echo get_avatar_url( get_avatar( get_the_author_meta( 'ID' ), 150 ) ); ?>" />
<span itemprop="name"><?php the_author();?></span>
</div>
 
</header>
 
<div itemprop="text">
<?php the_content(); ?>
</div>
 
</article>

**Comment by ineagu** [comment]
@abaicus learned that you can do this and it works amazing with : https://pt.wordpress.org/plugins/schema/, not sure if we need to do this in the theme..

**Comment by abaicus** [comment]
whichever way you think it would be better :D
