### ISSUE TITLE
Debugging errors in WordPress 4.8

### ISSUE THREAD

**Issue by suyogyashukla** [Codeinwp/zillah#170]
When in Customizer, I get the following error in console:
```
   Uncaught TypeError: Cannot read property 'offsetWidth' of undefined
    at c.slide (VM194 bootstrap.min.js?ver=20130115:6)
    at c.next (VM194 bootstrap.min.js?ver=20130115:6)
    at d (VM172 jquery.js?ver=1.12.4:2)
```

Update: I just noticed they appear outside the customizer too

cc @rodica-andronache @cristian-ungureanu

**Comment by HardeepAsrani** [comment]
Can't reproduce, inside or outside customizer, tried many installs, including a live one.
