### ISSUE TITLE
Fix Webmaster console errors and Show Sidebar on mobile

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/zillah#174]
A client received Hentry, hatom, hcard error in the Webmaster console. http://prntscr.com/gizec2

https://secure.helpscout.net/conversation/428637399/142533/?folderId=212390

+ Let's show the sidebar on mobile. Remove the current toggle https://prnt.sc/gk4sdq

**Comment by ineagu** [comment]
cc @bogdanpopa90 .

@rodica-andronache maybe we can fix this + show the sidebar on mobile instead hide it under a button
