### ISSUE TITLE
Footer is not showing in mobile devices.

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/zillah#180]
@rodica-andronache the footer only appears in desktop view, it's not showing in mobile devices. 

https://secure.helpscout.net/conversation/530303002/155710?folderId=212390

**Comment by rodica-andronache** [comment]
@poonam279 I think hiding the footer widgets area on mobile was a design decision, so I'm not sure we want to have it back. Did you see many users asking about this? :)
