### ISSUE TITLE
Big splace is displayed when slider and alternative layout is active.

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/zillah#185]
**Issues:**
1. http://prntscr.com/j24izj - Big space is there
2. http://prntscr.com/j24j79 - Screen srolls horizontally

**How to replicate:**
Add multiple posts in the slider and main content area on Homepage.
Enable slider and an alternative layout. Check the website on mobile screen.

Ticket: https://secure.helpscout.net/conversation/555847354/158636/

@rodica-andronache

**Comment by cosmin-serbanescu** [comment]
@Vishakha-Patel , cannot seem to replicate this one - are you sure you're not doing/adding anything else that generates that bug? tried it with the slider and blog posts/sample page as front page. Also from what I've seen the client complained about the slider not disappearing on mobile device but it actually does when the viewport is <992px.

**Comment by Vishakha-Patel** [comment]
@cosmin-serbanescu 

Do you have these options enabled?
http://prntscr.com/j3a5g7
http://prntscr.com/j3a5m5

Also, reload the page after resizing the window. Does it recreate it?

Other than this I don't have anything special. Only Pirate Forms plugin is there.

**Comment by cosmin-serbanescu** [comment]
Fixed it and figured out also what was that ajax call for.
cc @rodica-andronache
