### ISSUE TITLE
content classes

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zillah#22]
@claudiuvertistudio please mention here all the content classes you have used ( like .dropcap ), so our support team can add them into documentation .

We can also mention them in the demo, in a styleguide post.

**Comment by claudiuvertistudio** [comment]
.dropcap
blockquote.alignright
blockquote.alignleft
.highlight

**Comment by ineagu** [comment]
@mileamadalin who is working on documention here ?

**Comment by mileamadalin** [comment]
Hardeep

**Comment by rodica-andronache** [comment]
@HardeepAsrani please make sure you include this in the documentation :)

**Comment by HardeepAsrani** [comment]
Alright.
