### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zillah#27]
@claudiuvertistudio we are allowed to have just 1 footer link, so I would remove the link from Zillah, leave just as text and keep only the themeisle link

**Comment by rodica-andronache** [comment]
@ineagu here you wanted to remove the "Proudly powered by" link too, right? Keep only Theme Zillah by Themeisle

**Comment by ineagu** [comment]
nop, that link is ok .

On Mon, Jun 6, 2016 at 12:22 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> here you wanted to remove the
> "Proudly powered by" link too, right? Keep only Theme Zillah by Themeisle
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/zillah/issues/27#issuecomment-223921306>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABw6DPkf-zmXPqy3wqooRSvyuKqyXxd9ks5qI_TmgaJpZM4IpwQ7>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
ok, I thought we want to remove it. Like he said here https://github.com/Codeinwp/zillah/issues/57
