### ISSUE TITLE
Slider functionality

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zillah#31]
When choosing categories that don't have posts with images, the slider doesn't appear and I think it's confusing for the user. http://prntscr.com/bb13pi
Maybe should we display a message saying that the posts need to have featured images?
@ineagu

**Comment by ineagu** [comment]
can we still show the slider if there are only posts without images ? while
excluding them if there are any other with images ?

On Wed, Jun 1, 2016 at 4:13 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> When choosing categories that don't have posts with images, the slider
> doesn't appear and I think it's confusing for the user.
> http://prntscr.com/bb13pi
> Maybe should we display a message saying that the posts need to have
> featured images?
> @ineagu <https://github.com/ineagu>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/zillah/issues/31>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DF9YtnzSpbxtPxdktXH60a7Az3Xvks5qHZNxgaJpZM4IrlxP>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
@ineagu I don't understand what you mean here :)

**Comment by ineagu** [comment]
nevermind, maybe just mention in customizer that we don't show posts
without featured image :)

On Thu, Jun 2, 2016 at 10:53 AM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> I don't understand what you mean here
> :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/zillah/issues/31#issuecomment-223233492>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABw6DJBVbrgBhnLfDW22eyaqGQNrdQGMks5qHpoQgaJpZM4IrlxP>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
