### ISSUE TITLE
Banners Zillah pentru lansare

### ISSUE THREAD

**Issue by sab2ina** [Codeinwp/zillah#38]
Sa pregatim bannerele pentru lansarea Zillah - ar trebui sa contina logo-ul ThemeIsle + copy

"Fresh blogging theme for #WordPress. No email, no signup, go grab it!" 
"Brand new blogging theme for WordPress. No signup needed, just grab it!"

(poti sa ajustezi eventual copy-ul daca e prea lung) 

Le vom folosi pentru campaniile de retargeting - pt Facebook, Twitter si Perfect Audience

Pe 8, miercuri, ar trebui sa le avem ca sa dam drumul la campanii.

cc @ineagu @mariusghitulescu

**Comment by ineagu** [comment]
Pt fb twitter merge si o imagine cu tema si un buton de download, ca avem logo pe account + copy

**Comment by s2abina** [comment]
Linkul din bannere trebuie sa duca in LP, deci ar trebui sa fie gata cam in acelasi timp :)
