### ISSUE TITLE
Removal of Core Options

### ISSUE THREAD

**Issue by sakinshrestha** [Codeinwp/zillah#46]
- Theme must support all WordPress Core functionality.
- Theme removes Display header text checkbox functionality in `customizer.php` line 23. Theme needs to support this functionality rather than removing it.

**Comment by ineagu** [comment]
@sakin @justintadlock but wouldn't that just add more confusion? If we keep the default check with display title and tagline? Obviously nobody will show both the logo and the title + tagline. 

What we did what to rework the core functionality to display title + tagline by default and when logo is added just tagline. When is disabled nothing.

We just adapted the core functionality to the theme itself, leaving the core default and adding an extra option will just create confusion.

Can we get into w.org directory with this setup ?

**Comment by ineagu** [comment]
tnx for suggestion I will look into it. I am not saying that nobody is
using that, I am saying that more people have only one of those ( logo /
title ) rather than both.

On Wed, Jun 8, 2016 at 4:13 PM, Justin Tadlock <notifications@github.com>
wrote:

> Obviously nobody will show both the logo and the title + tagline.
>
> That's an assumption that I wouldn't make as a theme designer. I've worked
> with many users over the years who display both the logo and the title +
> tagline.
>
> Can we get into w.org directory with this setup ?
>
> You won't be able to if you're removing core customizer controls, which is
> why Sakin pointed it out.
> ------------------------------
>
> What you can do is may set header-text to false for your Custom Header.
> Then, set the header-text argument for Custom Logo.
>
> That's something I'd work with.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/zillah/issues/46#issuecomment-224584304>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABw6DHkZ4FbjTUmvdZJxKZPOJMU2frjrks5qJr_ngaJpZM4IsuvO>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by sakinshrestha** [comment]
Yes, if you are just selling this theme as Premium Theme then it's not a problem but in WordPress.org you are not allowed to remove WordPress core functions. I think there is no harm in making `header-text` to `false`. On the positive side, there might me like about 5% who like to have both Header Text and Logo Together.

**Comment by ineagu** [comment]
Thanks for help, we didn't know about that parameter!

I have some other thing that I am not sure about, regarding guidelines. Can
we add a setting in the theme to pick 1st image from post in case featured
image doesn't exist ?

I don't see it plugin territory or something, I just want to be sure :)

On Wed, Jun 8, 2016 at 7:14 PM, Sakin Shrestha <notifications@github.com>
wrote:

> Yes, if you are just selling this theme as Premium Theme then it's not a
> problem but in WordPress.org you are not allowed to remove WordPress core
> functions. I think there is no harm in making header-text to false. On
> the positive side, there might me like about 5% who like to have both
> Header Text and Logo Together.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/zillah/issues/46#issuecomment-224643032>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABw6DBkBEJqKSPMMU0CvoX6eFGNq3-gFks5qJupagaJpZM4IsuvO>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by justintadlock** [comment]
> I have some other thing that I am not sure about, regarding guidelines. Can we add a setting in the theme to pick 1st image from post in case featured image doesn't exist ?

Sure.  That's entirely design-related.  I have a similar script myself.
