### ISSUE TITLE
clicking on the search widget open the header widget

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zillah#6]
clicking on the search widget open the header widget

**Comment by rodica-andronache** [comment]
@ineagu I don't understand here? Could you please give more details?

**Comment by ineagu** [comment]
go to widgets, add a search widget, click on it on frontend .

On Mon, May 9, 2016 at 2:29 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> I don't understand here? Could you
> please give more details?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zillah/issues/6#issuecomment-217851010>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
