### ISSUE TITLE
Landing Page Zillah

### ISSUE THREAD

**Issue by sab2ina** [Codeinwp/zillah#71]
Mergem pe formatul nou de LP, in care mai trebuie sa iti dam noi:
- exemple site-uri cu Zillah (o sa fie pe blogul ThemeIsle)
- 2 review-uri 
- scoatem WooCommerce

cc @ineagu

**Comment by s2abina** [comment]
Site-urile pe care o sa avem Zillah (am vorbit cu Adleina pt descrieri):
http://themeisle.com/blog/
http://ionutn.com/
http://www.alyonatravels.com
http://inspiredm.com/
http://madalinm.com/

**Comment by selu91** [comment]
pot sa o pun si eu daca imi fac blog ? :)) ?

**Comment by ineagu** [comment]
da, toata lumea blog

On Tue, Jun 7, 2016 at 6:24 PM, Marius Cristea <notifications@github.com>
wrote:

> pot sa o pun si eu daca imi fac blog ? :)) ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/zillah/issues/71#issuecomment-224316313>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABw6DBQFGB4K9ryGBlqANcQz0_HNZbTbks5qJY1IgaJpZM4IuwP0>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
