### ISSUE TITLE
em issues

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zillah#97]
@claudiuvertistudio while mobile looks quite ok in term of fonts, if you look on dev2 , category font-size from slider + sidebar font sizes are too small now.

Make sure you adjust the em/rem to match the previous font-size on desktop.

Also we need em for quotes which now looks too big on mobile.

**Comment by rodica-andronache** [comment]
@claudiuvertistudio on mobile there is no slider or sidebar right?

**Comment by claudiuvertistudio** [comment]
Yes
